Add work-about sections
Behnam1369/Portfolio pull request #2
Opened 2022-01-06 21:10 UTC by Behnam1369

2022-01-06 21:17 UTC, leolpaz reviewed
Hi @Behnam1369 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not contain a short summary of what was added in the PR description
![image](https://user-images.githubusercontent.com/73140461/148453313-dba2548c-c72a-4dde-8cf2-0ae5652f1179.png)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-01-06 22:53 UTC, Lordkaito requested changes
Hi @Behnam1369, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-06 22:53 UTC, Lordkaito commented on index.html
> +                    <span class="tag">javascript</span>
- [ ] Please, make sure to use `<ul>` tags for your languages here and the correspondent `<li>` tag as well. This is really helpful to make your code more semantic, so later on, whenever you (or any other developer) see your project you can understand it without struggling.

2022-01-06 22:53 UTC, Lordkaito commented on index.html
> +                <span >Follow me on social media</span>
- [ ] Kindly use `<hx>` tags for subtitles like this one. As I mentioned earlier, this helps your code to be more semantic.

2022-01-06 22:53 UTC, Lordkaito commented on index.html
> +                <h3>Skills</h3>
- [ ] Please change these `<h3>` tags that you used for "Languages", "Frameworks" and "Skills" into a `<li>` tags, and remember to put them all together into a `<ul>`. The result should be a nested `<ul>` (one `<ul>` inside another `<ul>`) between "Languages" and "JavaScript", "HTML" and "CSS", for example.

2022-01-07 15:36 UTC, Behnam1369 commented
- Use list tags instead of `span` for tag class
- Use `h5` instead of `span` for subtitle
- Use nested lists in the technologies used section.

2022-01-07 15:43 UTC, ReshyResh approved these changes
# Hi @Behnam1369 , 

### You did a wonderful job implementing the requested changes!
#### Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

----

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

2022-01-07 16:28 UTC, merged